version: "2.1"
services:
  app:
    build: .
    networks:
      - esnet
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: elasticsearch:9300
      WAIT_HOSTS_TIMEOUT: 300
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    restart: always
    networks:
      - esnet
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esvolume:/usr/share/elasticsearch/data
    environment:
      - cluster.name=google
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
  esvolume:
    driver: local

networks:
  esnet: